# Generated by Django 3.1.2 on 2020-10-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201003_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Ord',
        ),
    ]
